### ISSUE TITLE
Variable decimal spaces?

### ISSUE THREAD

**Issue by brandonweiss** [soffes/Motivation#1]
The last digit is going so fast it's kind of stressing me out :) A setting for controlling how many decimal places to show would be awesome!

**Comment by soffes** [comment]
It's supposed to terrify you :)

I'll try to add this soon though.

**Comment by brandonweiss** [comment]
Hahaha. Thanks!

**Comment by brandonweiss** [comment]
:dancer::dancer::dancer:
